version: '3'

services:
  slimapp:
    image: bhboruff/php-composer
    environment:
      user: "${UID}:${GID}"
      # NB: the default for PHP_OPCACHE_VALIDATE_TIMESTAMPS is 0, which may be what you
      # want for production, but for dev you certainly want file changes to be detected, thus set to 1
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
    ports:
      - 8000:8000
    volumes:
      - .:/code
    command: php -S 0.0.0.0:8000 -t public
