version: '3'

services:
    slimapp:
        image: bhboruff/php-composer
        environment:
            user: "${UID}:${GID}"
        ports:
            - 8000:8000
        volumes:
            - .:/code/app
        command: php -S 0.0.0.0:8000 -t public
